package main

import (
	"crypto/rand"
	"fmt"
	"math/big"
	//	"math/rand"
)

func main() {
	fmt.Println("Maths in golang")

	// Random Numbers can be generated by math and crypto(Good Algorithm)
	// rand.Seed(time.Now().UnixNano())
	// fmt.Println(rand.Intn(5) + 1)

	//from crypto
	myRandomnum, _ := rand.Int(rand.Reader, big.NewInt(5))
	fmt.Println(myRandomnum)
}
